import type { MEETING_TYPE_CODES } from "@mymeetingapp/shared";

export type MeetingTypeCode = (typeof MEETING_TYPE_CODES)[number];

// English names from the Meeting Guide spec (github.com/code4recovery/spec data/types.json, 2026-09), one per code the
// API returns. A code added to the shared list fails typecheck here until it has a name.
export const TYPE_LABELS: Record<MeetingTypeCode, string> = {
  "11": "11th Step Meditation",
  "12x12": "12 Steps & 12 Traditions",
  A: "Secular",
  ABSI: "As Bill Sees It",
  AF: "Afrikaans",
  AL: "Concurrent with Alateen",
  "AL-AN": "Concurrent with Al-Anon",
  AM: "Amharic",
  AR: "Arabic",
  ASL: "American Sign Language",
  B: "Big Book",
  BA: "Babysitting Available",
  BE: "Newcomer",
  BG: "Bulgarian",
  BI: "Bisexual",
  BRK: "Breakfast",
  C: "Closed",
  CAN: "Candlelight",
  CF: "Child-Friendly",
  D: "Discussion",
  DA: "Danish",
  DB: "Digital Basket",
  DD: "Dual Diagnosis",
  DE: "German",
  DR: "Daily Reflections",
  EL: "Greek",
  EN: "English",
  FA: "Persian",
  FI: "Finnish",
  FF: "Fragrance Free",
  FR: "French",
  G: "Gay",
  GR: "Grapevine",
  H: "Birthday",
  HE: "Hebrew",
  HI: "Hindi",
  HR: "Croatian",
  HU: "Hungarian",
  IS: "Icelandic",
  ITA: "Italian",
  JA: "Japanese",
  KA: "Georgian",
  KOR: "Korean",
  L: "Lesbian",
  LGBTQ: "LGBTQ",
  LIT: "Literature",
  LS: "Living Sober",
  LT: "Lithuanian",
  M: "Men",
  MED: "Meditation",
  ML: "Malayalam",
  MT: "Maltese",
  N: "Native American",
  NB: "Non-Binary",
  NDG: "Indigenous",
  NE: "Nepali",
  NL: "Dutch",
  NO: "Norwegian",
  O: "Open",
  OUT: "Outdoor",
  P: "Professionals",
  POA: "Proof of Attendance",
  POC: "People of Color",
  POL: "Polish",
  POR: "Portuguese",
  PUN: "Punjabi",
  RUS: "Russian",
  S: "Spanish",
  SEN: "Seniors",
  SK: "Slovak",
  SL: "Slovenian",
  SM: "Smoking Permitted",
  SP: "Speaker",
  ST: "Step Study",
  SV: "Swedish",
  T: "Transgender",
  TH: "Thai",
  TL: "Tagalog",
  TR: "Tradition Study",
  TUR: "Turkish",
  UK: "Ukrainian",
  W: "Women",
  X: "Wheelchair Access",
  XB: "Wheelchair-Accessible Bathroom",
  XT: "Cross Talk Permitted",
  Y: "Young People",
};

// The types offered as filters (decision 9); the meeting page shows all of them.
export const FILTER_TYPES: readonly MeetingTypeCode[] = [
  "O",
  "C",
  "BE",
  "W",
  "M",
  "Y",
  "LGBTQ",
  "S",
  "X",
  "SP",
  "D",
  "B",
  "ST",
  "MED",
];
